flask_test/app/main/views.py
#!/usr/bin/env python
# coding=utf-8

from flask import render_template, redirect, url_for, Blueprint, flash, request
from ..models import User, db, Role, Permission, Post
from ..decorators import admin_required
from flask_login import login_required, current_user
from .forms import EditProfileForm, EditProfileAdminForm, PostForm


main = Blueprint('main', __name__)


@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)


@main.route('/', methods=['POST', 'GET'])
def index():
    form = PostForm()
    if current_user.can(Permission.WRITE_ARTICLES) and form.validate_on_submit():
        # _get_current_object()为真正的用户对象
        post = Post(body=form.body.data, author=current_user._get_current_object())
        db.session.add(post)
        return redirect(url_for('main.index'))
    # posts = Post.query.order_by(Post.timestamp.desc()).all()
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=20, error_out=False)
    posts = pagination.items
    return render_template('index.html', form=form, posts=posts, pagination=pagination)


@main.route('/user/<username>', methods=['POST', 'GET'])
def user(username):
    u = User.query.filter(User.username == username).first()
    posts = u.posts.order_by(Post.timestamp.desc()).all()
    return render_template('auth/user_info.html', user=u, posts=posts)


@main.route('/edit-profile', methods=['POST', 'GET'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        db.session.add(current_user)
        flash(u'编辑成功')
        return redirect(url_for('.user', username=current_user.username))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    return render_template('auth/edit_info.html', form = form)


@main.route('/edit-profile/<int:uid>', methods=['POST', 'GET'])
@login_required
@admin_required
def edit_profile_admin(uid):
    u = User.query.get_or_404(uid)
    form = EditProfileAdminForm(user=user)
    if form.validate_on_submit():
        u.email = form.email.data
        u.username = form.username.data
        u.confirmed = form.confirmed.data
        u.role = Role.query.get(form.role.data)
        u.name = form.name.data
        u.location = form.location.data
        u.about_me = form.about_me.data
        db.session.add(u)
        return redirect(url_for('.user', username=u.username))
    form.email.data = u.email
    form.username.data = u.username
    form.confirmed.data = u.confirmed
    form.role.data = u.role_id
    form.name.data = u.name
    form.location.data = u.location
    form.about_me.data = u.about_me
    return render_template('auth/edit_info.html', form=form, user=u)

flask_test/app/templates/_posts.html
<ul class="posts">
    {% for post in posts %}
    <li class="post">
        <div class="post-thumbnail">
            <a href="{{ url_for('main.user', username=post.author.username) }}">
                <img src="{{ post.author.gravatar(size=40) }}" class="img-rounded profile-thumbnail">
            </a>
        </div>
        <div class="post-content">
            <div class="post-date">{{moment(post.timestamp).fromNow() }}</div>
            <div class="post-author"><a href="{{ url_for('main.user', username=post.author.username) }}">{{ post.author.username}}</a></div>
            <div class="post-body">{{ post.body}}</div>
        </div>
    </li>
    {% endfor %}
</ul>

flask_test/app/templates/base.html
{% extends "bootstrap/base.html" %}
{% block title %} cyaoda {% endblock title %}

{% block head %}
{{ super() }}
<link rel="shotcut icon" href="{{ url_for('static', filename = '5.jpg') }}" type="image/x-icon" >
<link rel="icon" href="{{ url_for('static', filename = '5.jpg') }}" type="image/x-icon" >
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" type="text/css">

{% endblock head %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Cyaoda -Blog</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">主页</a></li>
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('main.user', username=current_user.username) }}">个人中心</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">设置<span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{{ url_for('auth.alter_psw') }}">修改密码</a></li>
                    <li><a href="#">修改邮箱</a></li>
                      {% if current_user.is_authenticated %}
                      <li><a href="{{ url_for('main.edit_profile') }}">编辑个人信息</a></li>
                      {% endif %}
                      {% if current_user.is_adminitrator() %}
                      <li><a href="{{ url_for('main.edit_profile_admin', id=current_user.id) }}">编辑个人信息[Admin]</a></li>
                      {% endif %}
                    <li class="divider"></li>
                    <li class="dropdown-header"></li>
                    <li><a href="{{ url_for('auth.logout') }}">退出登陆</a></li>
                  </ul>
                </li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">登陆</a></li>
                <li><a href="{{ url_for('auth.register') }}">注册</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

{% if user==current_user %}
<div class="footer">
    <div class="container">
        <p class="text-muted" style="    margin-left: 100px">
            注册日期 {{ moment(user.member_since).format('L')}}.
            上次访问日期 {{ moment(user.last_seen).format('L') }}
        </p>
    </div>
</div>
{% endif %}
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alart alart-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
    </div>
    {% endfor %}
    {% block page_content %} {% endblock page_content %}
</div>

{% endblock content %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock scripts %}

flask_test/app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Cyaoda-Blog {% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>你好, {% if current_user.is_authenticated %} {{ current_user.username }}
        {% else %} 游客 {% endif %}!
    </h1>
</div>
<div>
    {% if current_user.can(Permission.WRITE_ARTICLES) %}
    {{ wtf.quick_form(form) }}
    {% endif %}
</div>
{% include '_posts.html' %}
{% endblock page_content %}